### ISSUE TITLE
Update Fee Tiers

### ISSUE THREAD

**Issue by partylikeits1983** [compolabs/orderbook-contract#135]
After doing some research, this fee structure is more representative of the fee tiers we will most likely use in production: 

### 30-Day Volume (USD) Fee Structure

| 30-Day Volume (USD)    | Maker Fee | Taker Fee |
|------------------------|-----------|-----------|
| $0 - $10,000           | 0.25%     | 0.40%     |
| $10,001 - $50,000      | 0.20%     | 0.35%     |
| $50,001 - $100,000     | 0.14%     | 0.24%     |
| $100,001 - $250,000    | 0.12%     | 0.22%     |
| $250,001 - $500,000    | 0.10%     | 0.20%     |
| $500,001 - $1,000,000  | 0.08%     | 0.18%     |
| $1,000,001 - $2,500,000| 0.06%     | 0.16%     |
| $2,500,001 - $5,000,000| 0.04%     | 0.14%     |
| $5,000,001 - $10,000,000| 0.02%    | 0.12%     |
| $10,000,000+           | 0.00%     | 0.10%     |

### Todo

- [ ]  Update deploy script
- [ ] Add test for this specific fee structure
- [ ] Add explicit test to set this fee structure
